DR_CFG_ZOOKEEPER_ENV_URL:
  10.18.19.64:12181,10.18.19.28:12181,10.18.19.61:12181

ZK_DOC_MANAGER_GROUP:
  /com/dianrong/cfg/1.0.0/plateaux/docmanager

mysql0.jdbc.url:
  jdbc:mysql://10.18.19.43:3307/drmain

mysql0.jdbc.username:
  drmain

mysql0.jdbc.password:
  hkH=kN3

mysql0.jdbc.maxActive:
  5

oracle0.jdbc.url:
  jdbc:oracle:thin:@//10.18.19.33:1521/dbdev2

oracle0.jdbc.username:
  sl_main

oracle0.jdbc.password:
  sl_main

oracle0.jdbc.maxActive:
  5

spring.batch.job.enabled:
  false

kafka.broker.address:
  localhost:9092

canal.ip:
  localhost

canal.port:
  11111

canal.destination:
  example

multipart.max-file-size: 20Mb
multipart.max-request-size: 20Mb
spring:
  profiles:
    active:


#CRM_ADDR:
  #http://cdservice.dianrong.com
  
#DOC_ROOT:
  #/tmp
